### ISSUE TITLE
What size server?

### ISSUE THREAD

**Issue by jessjaco** [digitalearthpacific/dep-tileserver#2]
All I know is t2.micro is too small.

**Comment by alexgleith** [comment]
Just pick CPU and RAM limits. Don't need to choose a server.

**Comment by alexgleith** [comment]
I explored this a little. When smashing a single server instance with one user, it maxed at 2 GB memory and less than 1 CPU.

I have us with 2 instances now, each with 3 GB of memory and 1 CPU requested. We should load test some time with a bunch of people, but it seems like it works fine.

If we really need to, we can add a CloudFront cache, but currently it's not necessary.

**Comment by alexgleith** [comment]
FYI, the resource requests are here: https://github.com/digitalearthpacific/dep-flux/blob/main/apps/base/tileserver/deployment.yaml#L23-L29

And the `replicas` field decides how many replicas.
